### ISSUE TITLE
UnboundLocalError: local variable 'ckpt_path' referenced before assignment

### ISSUE THREAD

**Issue by vinaybmore** [pascalxia/driver_attention_prediction#11]
I am facing this issue while generating Alexnet features .

to reproduce 

`python make_feature_maps.py \
--data_dir=data/training \
--model_dir=pretrained_models/model_for_inference
`
The traceback is here 
`Traceback (most recent call last):
  File "make_feature_maps.py", line 186, in <module>
    main(argv=sys.argv)
  File "make_feature_maps.py", line 163, in main
    checkpoint_path=ckpt_path)
UnboundLocalError: local variable 'ckpt_path' referenced before assignment`

**Comment by YCBjust** [comment]
Have you solved this problem?
